project_id = "cydqkoohhzesogvctvhy"

[functions.encrypted-audio-handler]
verify_jwt = false

[functions.encrypted-audio-api]
verify_jwt = false

[functions.data-export-handler]
verify_jwt = false

[functions.data-deletion-handler]
verify_jwt = false

[functions.storage-manager]
verify_jwt = false

[functions.admin-bulk-download]
verify_jwt = false

[functions.decrypt-download]
verify_jwt = false

[functions.openai-transcribe]
verify_jwt = false