project_id = "cydqkoohhzesogvctvhy"

[functions.encrypted-audio-handler]
verify_jwt = false

[functions.encrypted-audio-api]
verify_jwt = false

[functions.data-export-handler]
verify_jwt = true

[functions.data-deletion-handler]
verify_jwt = false

[functions.storage-manager]
verify_jwt = true

[functions.admin-bulk-download]
verify_jwt = true

[functions.decrypt-download]
verify_jwt = false

[functions.stt-openai]
verify_jwt = false

[functions.realtime-ephemeral]
verify_jwt = false

[functions.tts-elevenlabs]
verify_jwt = false